sudo: required
language: c
before_install:
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update
install:
    - sudo apt-get install gcc-arm-none-eabi
before_script: gcc-arm-none-eabi --version
script: make -C test/build
