sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-arm-none-eabi
      - libstdc++-arm-none-eabi-newlib
      
language: c
compiler: clang
before_script:
  - arm-none-eabi-gcc --version
script: make -C test/build

cache: apt
